### PR TITLE
Use named import

### PR DESCRIPTION
**Pull request by coryhouse**
I just cloned this repo and confirmed this works.

### CODE REVIEW

**Comment by retorquere** [comment]
I... have no idea why it didn't for me. It does now work.

**Comment by coryhouse** [comment]
Glad you're rolling! 👍

**Comment by retorquere** [comment]
Super thanks for being so responsive!

**Comment by retorquere** [comment]
Is there a stage-by-stage repo I could diff mine against? I've just finished 'Step through Redux Flow' and my saves aren't adding to the list.

**Comment by retorquere** [comment]
ne-ver-mind... there's a relevant difference between `[...state, Object.assign({}, action.course)]` and `[...state, Object.assign({}, action.source)]`

**Pull request merged**
